### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Sulley-Bear** [httnn/gruntfile-gen#3]
This is a fantastic web-app! :+1:

I was thinking it might be cool to reference from, or integrate with, the Grunt documentation.

However, your software hasn't been licensed.

Would you be able to add a license, in case we'd like to use it?

**Comment by Sulley-Bear** [comment]
Ping! @bodyflex

**Comment by Sulley-Bear** [comment]
Thanks so much!

**Comment by httnn** [comment]
you're welcome!

if you wish, I can add you (or someone else) as a collaborator since I don't have time to maintain this project myself right now.

**Comment by Sulley-Bear** [comment]
Thanks, that would be great! I'll get back to you if somebody else wants to help collaborate too.

**Comment by httnn** [comment]
gotcha, added you now!

**Comment by Sulley-Bear** [comment]
You legend :+1:
